//! Register map for the `AudioBatchAxi` AXI-Lite slave.
//! Generated by `dotnet run -- hardware <repo-root>` in hdl/Warp11.Effects.
//! Do not edit by hand — changes will be overwritten on next emit.

pub const APERTURE_BYTES: usize = 256;
pub const ID_OFFSET: usize = 0x000;
pub const ID_VALUE: u32 = 0xab12c001;
pub const START_OFFSET: usize = 0x000;
pub const START_BIT: u32 = 0;
pub const BUSY_OFFSET: usize = 0x004;
pub const BUSY_SHIFT: u32 = 0;
pub const BUSY_MASK: u32 = 0x1;
pub const DONE_IRQ_OFFSET: usize = 0x008;
pub const DONE_IRQ_BIT: u32 = 0;
pub const SRC_ADDR_OFFSET: usize = 0x00c;
pub const DST_ADDR_OFFSET: usize = 0x010;
pub const FRAME_COUNT_OFFSET: usize = 0x014;
pub const THRESHOLD_OFFSET: usize = 0x01c;
pub const RATIO_OFFSET: usize = 0x020;
pub const ATTACK_OFFSET: usize = 0x024;
pub const RELEASE_RATE_OFFSET: usize = 0x028;
pub const GAIN0_OFFSET: usize = 0x040;
pub const GAIN1_OFFSET: usize = 0x044;
pub const GAIN2_OFFSET: usize = 0x048;
pub const GAIN3_OFFSET: usize = 0x04c;
pub const GAIN4_OFFSET: usize = 0x050;
pub const GAIN5_OFFSET: usize = 0x054;
pub const GAIN6_OFFSET: usize = 0x058;
pub const GAIN7_OFFSET: usize = 0x05c;
