//! Register map for the `AudioEffectsAxi` AXI-Lite slave.
//! Generated by `dotnet run -- hardware <repo-root>` in hdl/Warp11.Effects.
//! Do not edit by hand — changes will be overwritten on next emit.

pub const APERTURE_BYTES: usize = 256;
pub const VOLUME_OFFSET: usize = 0x000;
pub const VOLUME_WIDTH: u32 = 16;
pub const VOLUME_RESET: u32 = 0x100;
pub const MUTE_OFFSET: usize = 0x004;
pub const MUTE_WIDTH: u32 = 1;
pub const MUTE_RESET: u32 = 0x0;
pub const EQ_B0_OFFSET: usize = 0x008;
pub const EQ_B0_WIDTH: u32 = 32;
pub const EQ_B0_RESET: u32 = 0x40000000;
pub const EQ_B1_OFFSET: usize = 0x00c;
pub const EQ_B1_WIDTH: u32 = 32;
pub const EQ_B1_RESET: u32 = 0x0;
pub const EQ_B2_OFFSET: usize = 0x010;
pub const EQ_B2_WIDTH: u32 = 32;
pub const EQ_B2_RESET: u32 = 0x0;
pub const EQ_A1_OFFSET: usize = 0x014;
pub const EQ_A1_WIDTH: u32 = 32;
pub const EQ_A1_RESET: u32 = 0x0;
pub const EQ_A2_OFFSET: usize = 0x018;
pub const EQ_A2_WIDTH: u32 = 32;
pub const EQ_A2_RESET: u32 = 0x0;
pub const COMP_THRESHOLD_OFFSET: usize = 0x01c;
pub const COMP_THRESHOLD_WIDTH: u32 = 24;
pub const COMP_THRESHOLD_RESET: u32 = 0xffffff;
pub const COMP_RATIO_OFFSET: usize = 0x020;
pub const COMP_RATIO_WIDTH: u32 = 8;
pub const COMP_RATIO_RESET: u32 = 0x0;
pub const COMP_ATTACK_OFFSET: usize = 0x024;
pub const COMP_ATTACK_WIDTH: u32 = 16;
pub const COMP_ATTACK_RESET: u32 = 0x0;
pub const COMP_RELEASE_OFFSET: usize = 0x028;
pub const COMP_RELEASE_WIDTH: u32 = 16;
pub const COMP_RELEASE_RESET: u32 = 0x0;
pub const COMP_MAKEUP_OFFSET: usize = 0x02c;
pub const COMP_MAKEUP_WIDTH: u32 = 16;
pub const COMP_MAKEUP_RESET: u32 = 0x100;
pub const LIMIT_THRESHOLD_OFFSET: usize = 0x030;
pub const LIMIT_THRESHOLD_WIDTH: u32 = 24;
pub const LIMIT_THRESHOLD_RESET: u32 = 0x7fffff;
