//! Register map for the `AudioGainAxi` AXI-Lite slave.
//! Generated by `dotnet run -- hardware <repo-root>` in hdl/Warp11.Effects.
//! Do not edit by hand — changes will be overwritten on next emit.

pub const APERTURE_BYTES: usize = 256;
pub const VOLUME_OFFSET: usize = 0x000;
pub const MUTE_OFFSET: usize = 0x004;
