//! Register map for the `AudioPassthruAxi` AXI-Lite slave.
//! Generated by `dotnet run -- hardware <repo-root>` in hdl/Warp11.Effects.
//! Do not edit by hand — changes will be overwritten on next emit.

pub const APERTURE_BYTES: usize = 256;
pub const MUTE_OFFSET: usize = 0x000;
pub const RECEIVED_COUNT_OFFSET: usize = 0x004;
pub const RECEIVED_COUNT_SHIFT: u32 = 0;
pub const RECEIVED_COUNT_MASK: u32 = 0xffffffff;
pub const LAST_LEFT_OFFSET: usize = 0x008;
pub const LAST_LEFT_SHIFT: u32 = 0;
pub const LAST_LEFT_MASK: u32 = 0xffffff;
