//! Register map for the `AudioEffectsAxi` AXI-Lite slave.
//! Generated by `dotnet run -- hardware <repo-root>` in hdl/Warp11.Effects.
//! Do not edit by hand — changes will be overwritten on next emit.

pub const APERTURE_BYTES: usize = 256;
pub const VOLUME_OFFSET: usize = 0x000;
pub const MUTE_OFFSET: usize = 0x004;
pub const EQ_B0_OFFSET: usize = 0x008;
pub const EQ_B1_OFFSET: usize = 0x00c;
pub const EQ_B2_OFFSET: usize = 0x010;
pub const EQ_A1_OFFSET: usize = 0x014;
pub const EQ_A2_OFFSET: usize = 0x018;
pub const COMP_THRESHOLD_OFFSET: usize = 0x01c;
pub const COMP_RATIO_OFFSET: usize = 0x020;
pub const COMP_ATTACK_OFFSET: usize = 0x024;
pub const COMP_RELEASE_OFFSET: usize = 0x028;
pub const COMP_MAKEUP_OFFSET: usize = 0x02c;
pub const LIMIT_THRESHOLD_OFFSET: usize = 0x030;
