//! Register map for the `GepClusterAxi` AXI-Lite slave — the WarpCPU
//! genetic-programming cluster. Population, pairing entries, the op-list
//! and the result ring all live in PS DDR; only control words cross
//! AXI-Lite, and the fitness table never leaves the fabric.
//! Generated by `dotnet run -- hardware <repo-root>` in hdl/Warp11.Gep.
//! Do not edit by hand — changes will be overwritten on next emit.

pub const APERTURE_BYTES: usize = 1024;
pub const START_QUEUE_OFFSET: usize = 0x000;
pub const START_QUEUE_BIT: u32 = 0;
pub const LD_CASE_OFFSET: usize = 0x000;
pub const LD_CASE_BIT: u32 = 1;
pub const QUEUE_BASE_OFFSET: usize = 0x004;
pub const POP_BASE_OFFSET: usize = 0x008;
pub const RING_BASE_OFFSET: usize = 0x00c;
pub const QUEUE_MASK_OFFSET: usize = 0x010;
pub const RING_MASK_OFFSET: usize = 0x014;
pub const ENTRIES_PUBLISHED_OFFSET: usize = 0x018;
pub const N_CASES_OFFSET: usize = 0x01c;
pub const CASE_ADDR_OFFSET: usize = 0x020;
pub const CASE_FIELD_OFFSET: usize = 0x024;
pub const CASE_DATA_OFFSET: usize = 0x028;
pub const RUNNING_OFFSET: usize = 0x02c;
pub const RUNNING_SHIFT: u32 = 0;
pub const RUNNING_MASK: u32 = 0x1;
pub const ALL_IDLE_OFFSET: usize = 0x02c;
pub const ALL_IDLE_SHIFT: u32 = 1;
pub const ALL_IDLE_MASK: u32 = 0x2;
pub const RESULTS_DONE_OFFSET: usize = 0x030;
pub const RESULTS_DONE_SHIFT: u32 = 0;
pub const RESULTS_DONE_MASK: u32 = 0xffffffff;
pub const ENTRIES_TAKEN_OFFSET: usize = 0x034;
pub const ENTRIES_TAKEN_SHIFT: u32 = 0;
pub const ENTRIES_TAKEN_MASK: u32 = 0xffffffff;
pub const CYCLE_COUNT_OFFSET: usize = 0x038;
pub const CYCLE_COUNT_SHIFT: u32 = 0;
pub const CYCLE_COUNT_MASK: u32 = 0xffffffff;
pub const FEED_STALL_CYCLES_OFFSET: usize = 0x03c;
pub const FEED_STALL_CYCLES_SHIFT: u32 = 0;
pub const FEED_STALL_CYCLES_MASK: u32 = 0xffffffff;
pub const BREEDER_STALL_CYCLES_OFFSET: usize = 0x040;
pub const BREEDER_STALL_CYCLES_SHIFT: u32 = 0;
pub const BREEDER_STALL_CYCLES_MASK: u32 = 0xffffffff;
pub const FILL_BUSY_CYCLES_OFFSET: usize = 0x044;
pub const FILL_BUSY_CYCLES_SHIFT: u32 = 0;
pub const FILL_BUSY_CYCLES_MASK: u32 = 0xffffffff;
pub const PACK_BUSY_CYCLES_OFFSET: usize = 0x048;
pub const PACK_BUSY_CYCLES_SHIFT: u32 = 0;
pub const PACK_BUSY_CYCLES_MASK: u32 = 0xffffffff;
pub const EMIT_BUSY_CYCLES_OFFSET: usize = 0x04c;
pub const EMIT_BUSY_CYCLES_SHIFT: u32 = 0;
pub const EMIT_BUSY_CYCLES_MASK: u32 = 0xffffffff;
pub const BUSY_BREEDER_CYCLES_OFFSET: usize = 0x050;
pub const BUSY_BREEDER_CYCLES_SHIFT: u32 = 0;
pub const BUSY_BREEDER_CYCLES_MASK: u32 = 0xffffffff;
pub const BUSY_LANE_CYCLES_OFFSET: usize = 0x054;
pub const BUSY_LANE_CYCLES_SHIFT: u32 = 0;
pub const BUSY_LANE_CYCLES_MASK: u32 = 0xffffffff;
pub const STREAMS_ACTIVE_OFFSET: usize = 0x058;
pub const STREAMS_ACTIVE_SHIFT: u32 = 0;
pub const STREAMS_ACTIVE_MASK: u32 = 0x7;
pub const AUTO_MODE_OFFSET: usize = 0x060;
pub const AUTO_POP_OFFSET: usize = 0x064;
pub const AUTO_GENS_OFFSET: usize = 0x068;
pub const AUTO_SIGMA_OFFSET: usize = 0x080;
pub const AUTO_RANGE_OFFSET: usize = 0x084;
pub const AUTO_R0_OFFSET: usize = 0x06c;
pub const AUTO_R1_OFFSET: usize = 0x070;
pub const AUTO_R2_OFFSET: usize = 0x074;
pub const AUTO_R3_OFFSET: usize = 0x078;
pub const AUTO_R4_OFFSET: usize = 0x07c;
pub const AUTO_S0_OFFSET: usize = 0x088;
pub const AUTO_S1_OFFSET: usize = 0x08c;
pub const AUTO_S2_OFFSET: usize = 0x090;
pub const AUTO_S3_OFFSET: usize = 0x094;
pub const AUTO_ROUND_OFFSET: usize = 0x098;
pub const AUTO_ROUND_SHIFT: u32 = 0;
pub const AUTO_ROUND_MASK: u32 = 0xffffffff;
pub const AUTO_DONE_OFFSET: usize = 0x09c;
pub const AUTO_DONE_SHIFT: u32 = 0;
pub const AUTO_DONE_MASK: u32 = 0x1;
pub const AUTO_BASE_OFFSET: usize = 0x09c;
pub const AUTO_BASE_SHIFT: u32 = 1;
pub const AUTO_BASE_MASK: u32 = 0x2;
pub const BEST_IDX_OFFSET: usize = 0x0a0;
pub const BEST_IDX_SHIFT: u32 = 0;
pub const BEST_IDX_MASK: u32 = 0xffff;
pub const BEST_FIT_LO_OFFSET: usize = 0x0a4;
pub const BEST_FIT_LO_SHIFT: u32 = 0;
pub const BEST_FIT_LO_MASK: u32 = 0xffffffff;
pub const BEST_FIT_HI_OFFSET: usize = 0x0a8;
pub const BEST_FIT_HI_SHIFT: u32 = 0;
pub const BEST_FIT_HI_MASK: u32 = 0xffffffff;
pub const OPLIST_DONE_OFFSET: usize = 0x09c;
pub const OPLIST_DONE_SHIFT: u32 = 2;
pub const OPLIST_DONE_MASK: u32 = 0x4;
pub const OPLIST_BASE_OFFSET: usize = 0x0b4;
pub const SKIP_SCORE_OFFSET: usize = 0x0b8;
pub const RNG_CONTINUE_OFFSET: usize = 0x0bc;
pub const BREEDER0_BUSY_CYCLES_OFFSET: usize = 0x100;
pub const BREEDER0_BUSY_CYCLES_SHIFT: u32 = 0;
pub const BREEDER0_BUSY_CYCLES_MASK: u32 = 0xffffffff;
pub const BREEDER1_BUSY_CYCLES_OFFSET: usize = 0x104;
pub const BREEDER1_BUSY_CYCLES_SHIFT: u32 = 0;
pub const BREEDER1_BUSY_CYCLES_MASK: u32 = 0xffffffff;
pub const BREEDER2_BUSY_CYCLES_OFFSET: usize = 0x108;
pub const BREEDER2_BUSY_CYCLES_SHIFT: u32 = 0;
pub const BREEDER2_BUSY_CYCLES_MASK: u32 = 0xffffffff;
pub const BREEDER3_BUSY_CYCLES_OFFSET: usize = 0x10c;
pub const BREEDER3_BUSY_CYCLES_SHIFT: u32 = 0;
pub const BREEDER3_BUSY_CYCLES_MASK: u32 = 0xffffffff;
pub const LANE0_BUSY_CYCLES_OFFSET: usize = 0x180;
pub const LANE0_BUSY_CYCLES_SHIFT: u32 = 0;
pub const LANE0_BUSY_CYCLES_MASK: u32 = 0xffffffff;
pub const LANE1_BUSY_CYCLES_OFFSET: usize = 0x184;
pub const LANE1_BUSY_CYCLES_SHIFT: u32 = 0;
pub const LANE1_BUSY_CYCLES_MASK: u32 = 0xffffffff;
pub const LANE2_BUSY_CYCLES_OFFSET: usize = 0x188;
pub const LANE2_BUSY_CYCLES_SHIFT: u32 = 0;
pub const LANE2_BUSY_CYCLES_MASK: u32 = 0xffffffff;
pub const LANE3_BUSY_CYCLES_OFFSET: usize = 0x18c;
pub const LANE3_BUSY_CYCLES_SHIFT: u32 = 0;
pub const LANE3_BUSY_CYCLES_MASK: u32 = 0xffffffff;
pub const LANE4_BUSY_CYCLES_OFFSET: usize = 0x190;
pub const LANE4_BUSY_CYCLES_SHIFT: u32 = 0;
pub const LANE4_BUSY_CYCLES_MASK: u32 = 0xffffffff;
pub const LANE5_BUSY_CYCLES_OFFSET: usize = 0x194;
pub const LANE5_BUSY_CYCLES_SHIFT: u32 = 0;
pub const LANE5_BUSY_CYCLES_MASK: u32 = 0xffffffff;
pub const LANE6_BUSY_CYCLES_OFFSET: usize = 0x198;
pub const LANE6_BUSY_CYCLES_SHIFT: u32 = 0;
pub const LANE6_BUSY_CYCLES_MASK: u32 = 0xffffffff;
pub const LANE7_BUSY_CYCLES_OFFSET: usize = 0x19c;
pub const LANE7_BUSY_CYCLES_SHIFT: u32 = 0;
pub const LANE7_BUSY_CYCLES_MASK: u32 = 0xffffffff;

pub const N_BREEDERS: usize = 4;
pub const N_LANES: usize = 8;
pub const N_FILLERS: usize = 2;
pub const N_THREADS: usize = 16;
pub const GENE_LEN: usize = 17;
pub const HEAD_LEN: usize = 8;
pub const CONST_COUNT: usize = 4;
pub const VAR_COUNT: usize = 4;
pub const CAPACITY: usize = 32;
pub const CASE_CAPACITY: usize = 256;
pub const AUTO_POP_CAPACITY: usize = 1024;
pub const INLINE_PARENTS: bool = true;

/// A gene record, a pairing entry and an op-list entry are all this many
/// 32-bit words — 64 B, four 128-bit beats.
pub const RECORD_WORDS: usize = 16;
pub const RECORD_BYTES: usize = 64;
/// An inline-parent work item is the entry plus both parent records —
/// 192 B of payload on a 256 B STRIDE. The padding is what lets the
/// fabric fetch the whole item as one 12-beat burst: an AXI burst may
/// not cross a 4 KB boundary, and 256 divides 4096 where 192 does not.
pub const WORK_ITEM_WORDS: usize = 64;
pub const WORK_ITEM_BYTES: usize = 256;
pub const WORK_ITEM_PAYLOAD_WORDS: usize = 48;
pub const WORK_ITEM_BEATS: usize = 12;
/// One fitness-ring record: [fit_lo, fit_hi, entry_id, seq].
pub const RESULT_WORDS: usize = 4;
pub const RESULT_BYTES: usize = 16;
/// Words per packed individual as a lane consumes it (header, padded
/// program, constants), 16 B-aligned.
pub const INDIV_WORDS: usize = 40;

/// Pairing-entry flags, word 7's high half.
pub const FLAG_SKIP_WRITEBACK: u32 = 1;

/// Word indices inside a pairing entry — the one layout the fabric's
/// filler, the fabric's op-list emitter and the host marshaller share.
pub const ENTRY_PARENT_A: usize = 0;
pub const ENTRY_PARENT_B: usize = 1;
pub const ENTRY_DEST: usize = 2;
pub const ENTRY_RATE0: usize = 3; // ..RATE0+3; word 7 is flags<<16 | geneRecomb
pub const ENTRY_FLAGS_WORD: usize = 7;
pub const ENTRY_SIGMA: usize = 8;
pub const ENTRY_RANGE: usize = 9;
pub const ENTRY_ID: usize = 10;
pub const ENTRY_SEED0: usize = 12; // ..SEED0+3

/// Word indices inside a gene record.
pub const RECORD_SYMBOLS: usize = 1; // 4 symbols per word
pub const RECORD_CONSTANTS: usize = 10;
