//! Register map for the `GolAxi` AXI-Lite slave (Game of Life 64x64,
//! DDR triple-buffer snapshot at FB_BASE_ADDR's value).
//! Generated by `dotnet run -- hardware <repo-root>` in hdl/Warp11.GoL.
//! Do not edit by hand — changes will be overwritten on next emit.

pub const APERTURE_BYTES: usize = 1024;
pub const ID_OFFSET: usize = 0x000;
pub const ID_VALUE: u32 = 0xf5601001;
pub const LOAD_OFFSET: usize = 0x000;
pub const LOAD_BIT: u32 = 0;
pub const TICK_OFFSET: usize = 0x000;
pub const TICK_BIT: u32 = 1;
pub const RESET_OFFSET: usize = 0x000;
pub const RESET_BIT: u32 = 2;
pub const STOP_OFFSET: usize = 0x000;
pub const STOP_BIT: u32 = 3;
pub const BUSY_OFFSET: usize = 0x004;
pub const BUSY_SHIFT: u32 = 0;
pub const BUSY_MASK: u32 = 0x1;
pub const POPULATION_OFFSET: usize = 0x004;
pub const POPULATION_SHIFT: u32 = 1;
pub const POPULATION_MASK: u32 = 0x3ffe;
pub const GENERATION_OFFSET: usize = 0x008;
pub const GENERATION_SHIFT: u32 = 0;
pub const GENERATION_MASK: u32 = 0xffffffff;
pub const TICK_COUNT_OFFSET: usize = 0x00c;
pub const BURST_IRQ_OFFSET: usize = 0x010;
pub const BURST_IRQ_BIT: u32 = 0;
pub const SNAP_IRQ_OFFSET: usize = 0x010;
pub const SNAP_IRQ_BIT: u32 = 1;
pub const SNAP_CAPTURE_OFFSET: usize = 0x014;
pub const SNAP_CAPTURE_BIT: u32 = 0;
pub const SNAP_RELEASE_OFFSET: usize = 0x018;
pub const SNAP_RELEASE_BIT: u32 = 0;
pub const SNAP_READY_OFFSET: usize = 0x01c;
pub const SNAP_READY_SHIFT: u32 = 0;
pub const SNAP_READY_MASK: u32 = 0x1;
pub const SNAP_OVERRUN_OFFSET: usize = 0x01c;
pub const SNAP_OVERRUN_SHIFT: u32 = 8;
pub const SNAP_OVERRUN_MASK: u32 = 0xff00;
pub const SNAP_SLOT_OFFSET: usize = 0x01c;
pub const SNAP_SLOT_SHIFT: u32 = 16;
pub const SNAP_SLOT_MASK: u32 = 0x30000;
pub const INTERVAL_CYCLES_OFFSET: usize = 0x020;
pub const FB_BASE_ADDR_OFFSET: usize = 0x024;
pub const LOAD_ROW_OFFSET: usize = 0x200;
pub const LOAD_ROW_WORDS: usize = 128;

pub const GENS_PER_CYCLE: usize = 3;
pub const GRID_WIDTH: usize = 64;
pub const GRID_HEIGHT: usize = 64;
pub const ROWS_PER_BEAT: usize = 2;
pub const BEAT_COUNT: usize = 32;
pub const FRAME_BYTES: usize = 512;
pub const SLOT_STRIDE_BYTES: usize = 512;
pub const SLOT_COUNT: usize = 3;
