//! Register map for the `MandelPodAxi` AXI-Lite slave
//! (addrWidth=15, aperture 32768 bytes).
//! Generated by `dotnet run -- hardware <repo-root>` in hdl.
//! Do not edit by hand — changes will be overwritten on next emit.

pub const ID_OFFSET: usize = 0x00;
pub const ID_MAGIC: u32 = 0xf5b0d001;
pub const DONE_OFFSET: usize = 0x04;
pub const RESULT_COUNT_OFFSET: usize = 0x08;
pub const SCRATCH_OFFSET: usize = 0x0c;
pub const FRAME_CYCLES_OFFSET: usize = 0x10;
pub const FB_OFFSET: usize = 0x4000;
pub const FB_WINDOW_WORDS: usize = 4096;
pub const FB_PIXELS: usize = 3072;
pub const APERTURE_BYTES: usize = 32768;
pub const FRAME_WIDTH: usize = 64;
pub const FRAME_HEIGHT: usize = 48;
pub const MAX_ITER: u32 = 48;
