//! Register map for the `MandelFrameAxi` AXI-Lite slave (the full-scale
//! frame accelerator; addrWidth=12). The framebuffer is NOT in the
//! aperture — the fabric writes it to PS DDR at FB_BASE_ADDR_OFFSET's value.
//! Generated by `dotnet run -- hardware <repo-root>` in hdl.
//! Do not edit by hand — changes will be overwritten on next emit.

// The register half comes off the same map that elaborates the slave, so
// nothing here can drift from the fabric — which the hand-written version
// this replaced could, a register at a time. 0x000 reads as the identity
// and writes the start pulse; DONE is sticky, cleared by start.

pub const APERTURE_BYTES: usize = 4096;
pub const ID_OFFSET: usize = 0x000;
pub const ID_VALUE: u32 = 0xf5b0d002;
pub const START_OFFSET: usize = 0x000;
pub const START_BIT: u32 = 0;
pub const BUSY_OFFSET: usize = 0x004;
pub const BUSY_SHIFT: u32 = 0;
pub const BUSY_MASK: u32 = 0x1;
pub const DONE_OFFSET: usize = 0x008;
pub const DONE_SHIFT: u32 = 0;
pub const DONE_MASK: u32 = 0x1;
pub const CX_ORIGIN_OFFSET: usize = 0x00c;
pub const CY_ORIGIN_OFFSET: usize = 0x010;
pub const DX_OFFSET: usize = 0x014;
pub const DY_OFFSET: usize = 0x018;
pub const FRAME_CYCLES_OFFSET: usize = 0x01c;
pub const FRAME_CYCLES_SHIFT: u32 = 0;
pub const FRAME_CYCLES_MASK: u32 = 0xffffffff;
pub const FB_BASE_ADDR_OFFSET: usize = 0x020;
pub const LAYOUT_HASH_OFFSET: usize = 0x024;
pub const LAYOUT_HASH_VALUE: u32 = 0x00003655;

pub const FRAME_WIDTH: usize = 1400;
pub const FRAME_HEIGHT: usize = 800;
pub const WIDTH_PADDED: usize = 1408;
pub const FB_BYTES: usize = 1126400; // 1 byte/px, rows padded
pub const MAX_ITER: u32 = 256;
pub const NUM_LANES: usize = 104;
pub const FRAC_BITS: u32 = 28;
