//! Register map for the `MandelFrameAxi` AXI-Lite slave (the full-scale
//! frame accelerator; addrWidth=12). The framebuffer is NOT in the
//! aperture — the fabric writes it to PS DDR at FB_BASE_ADDR_OFFSET's value.
//! Generated by `dotnet run -- hardware <repo-root>` in hdl.
//! Do not edit by hand — changes will be overwritten on next emit.

pub const ID_OFFSET: usize = 0x00; // reads as ID; writes pulse start
pub const ID_MAGIC: u32 = 0xf5b0d002;
pub const START_OFFSET: usize = 0x00;
pub const BUSY_OFFSET: usize = 0x04;
pub const DONE_OFFSET: usize = 0x08; // sticky; cleared by start
pub const CX_ORIGIN_OFFSET: usize = 0x0c;
pub const CY_ORIGIN_OFFSET: usize = 0x10;
pub const DX_OFFSET: usize = 0x14;
pub const DY_OFFSET: usize = 0x18;
pub const LAST_FRAME_CYCLES_OFFSET: usize = 0x1c;
pub const FB_BASE_ADDR_OFFSET: usize = 0x20;
pub const APERTURE_BYTES: usize = 4096;
pub const FRAME_WIDTH: usize = 1400;
pub const FRAME_HEIGHT: usize = 800;
pub const WIDTH_PADDED: usize = 1408;
pub const FB_BYTES: usize = 1126400; // 1 byte/px, rows padded
pub const MAX_ITER: u32 = 256;
pub const NUM_LANES: usize = 104;
pub const FRAC_BITS: u32 = 28;
