module Warp11.Mandelbrot.Seam

open Warp11
open Warp11.Mandelbrot.Board
open Warp11.Mandelbrot.Pod
open Warp11.Mandelbrot.LanePod
open Warp11.Mandelbrot.FrameAxi

/// The generated Rust side of the seam: offsets, sizes and frame constants as
/// pub consts, no_std-clean, committed into the runtime crate so layout
/// changes show up in the driver's diff.
let private mandelLayoutRs () =
    String.concat
        "\n"
        [ "//! Register map for the `MandelPodAxi` AXI-Lite slave"
          $"//! (addrWidth=%d{apertureAddrWidth}, aperture %d{1 <<< apertureAddrWidth} bytes)."
          "//! Generated by `dotnet run -- hardware <repo-root>` in hdl."
          "//! Do not edit by hand — changes will be overwritten on next emit."
          ""
          $"pub const ID_OFFSET: usize = 0x%02x{idOffset};"
          $"pub const ID_MAGIC: u32 = 0x%08x{idMagic};"
          $"pub const DONE_OFFSET: usize = 0x%02x{doneOffset};"
          $"pub const RESULT_COUNT_OFFSET: usize = 0x%02x{resultCountOffset};"
          $"pub const SCRATCH_OFFSET: usize = 0x%02x{scratchOffset};"
          $"pub const FRAME_CYCLES_OFFSET: usize = 0x%02x{Pod.frameCyclesOffset};"
          $"pub const FB_OFFSET: usize = 0x%04x{fbOffset};"
          $"pub const FB_WINDOW_WORDS: usize = %d{1 <<< fbAddrWidth};"
          $"pub const FB_PIXELS: usize = %d{mandelWidth * mandelHeight};"
          $"pub const APERTURE_BYTES: usize = %d{1 <<< apertureAddrWidth};"
          $"pub const FRAME_WIDTH: usize = %d{mandelWidth};"
          $"pub const FRAME_HEIGHT: usize = %d{mandelHeight};"
          $"pub const MAX_ITER: u32 = %d{mandelMaxIter};"
          $"pub const FABRIC_HZ: u64 = %d{podBoard.fabricHz};"
          "" ]

/// The full-scale wrapper's generated Rust layout — the frame seam, same
/// pattern as the mini pod's.
let private mandelFrameLayoutRs () =
    let widthPadded = paddedWidth frameFullWidth

    let header =
        [ "//! Register map for the `MandelFrameAxi` AXI-Lite slave (the full-scale"
          $"//! frame accelerator; addrWidth=%d{frameApertureAddrWidth}). The framebuffer is NOT in the"
          "//! aperture — the fabric writes it to PS DDR at FB_BASE_ADDR_OFFSET's value."
          "//! Generated by `dotnet run -- hardware <repo-root>` in hdl."
          "//! Do not edit by hand — changes will be overwritten on next emit."
          ""
          "// The register half comes off the same map that elaborates the slave, so"
          "// nothing here can drift from the fabric — which the hand-written version"
          "// this replaced could, a register at a time. 0x000 reads as the identity"
          "// and writes the start pulse; DONE is sticky, cleared by start."
          "" ]

    // The geometry is the app's own, not the map's: `regMapRsLines` emits the
    // registers and the aperture, and the caller appends what a driver needs to
    // lay out DDR and size its transfers.
    let geometry =
        [ ""
          $"pub const FRAME_WIDTH: usize = %d{frameFullWidth};"
          $"pub const FRAME_HEIGHT: usize = %d{frameFullHeight};"
          $"pub const WIDTH_PADDED: usize = %d{widthPadded};"
          $"pub const FB_BYTES: usize = %d{frameFullHeight * widthPadded}; // 1 byte/px, rows padded"
          $"pub const MAX_ITER: u32 = %d{frameFullMaxIter};"
          $"pub const NUM_LANES: usize = %d{frameFullLanes};"
          $"pub const FRAC_BITS: u32 = %d{frameFullFracBits};"
          ""
          "// The clock this app's overlay programs, from the board the design was"
          "// built for. `frame_cycles` is only a time at this frequency, so a host"
          "// that wrote the number down separately could disagree with the fabric"
          "// about how fast the fabric is."
          $"pub const FABRIC_HZ: u64 = %d{frameBoard.fabricHz};"
          "" ]

    String.concat "\n" (header @ regMapRsLines frameMap @ geometry)

/// `dotnet run -- hardware <repo-root>`: the seam, emitted — both apps. The
/// Verilog goes where Vivado sources it; the layouts go where the Rust driver
/// owns them.
let writeHardware (repoRoot: string) =
    let buildDir = System.IO.Path.Combine(repoRoot, "hardware", "build")
    let runtimeSrc = System.IO.Path.Combine(repoRoot, "runtime", "core", "src")
    System.IO.Directory.CreateDirectory buildDir |> ignore

    let emitPair (verilogName: string) (design: ModuleDef) (layoutName: string) (layout: string) =
        let verilogPath = System.IO.Path.Combine(buildDir, verilogName)
        let layoutPath = System.IO.Path.Combine(runtimeSrc, layoutName)
        System.IO.File.WriteAllText(verilogPath, emitDesign design + "\n")
        System.IO.File.WriteAllText(layoutPath, layout)
        printfn $"wrote {verilogPath}"
        printfn $"wrote {layoutPath}"

    emitPair "MandelPodAxi.v" mandelPodAxi.def "mandel_layout.rs" (mandelLayoutRs ())
    emitPair "MandelFrameAxi.v" mandelFrameAxiFull.Value.def "mandel_frame_layout.rs" (mandelFrameLayoutRs ())
