module Warp11.Mandelbrot.Seam

open Warp11
open Warp11.Mandelbrot.Pod
open Warp11.Mandelbrot.LanePod
open Warp11.Mandelbrot.FrameAxi

/// The generated Rust side of the seam: offsets, sizes and frame constants as
/// pub consts, no_std-clean, committed into the runtime crate so layout
/// changes show up in the driver's diff.
let private mandelLayoutRs () =
    String.concat
        "\n"
        [ "//! Register map for the `MandelPodAxi` AXI-Lite slave"
          $"//! (addrWidth=%d{apertureAddrWidth}, aperture %d{1 <<< apertureAddrWidth} bytes)."
          "//! Generated by `dotnet run -- hardware <repo-root>` in hdl."
          "//! Do not edit by hand — changes will be overwritten on next emit."
          ""
          $"pub const ID_OFFSET: usize = 0x%02x{idOffset};"
          $"pub const ID_MAGIC: u32 = 0x%08x{idMagic};"
          $"pub const DONE_OFFSET: usize = 0x%02x{doneOffset};"
          $"pub const RESULT_COUNT_OFFSET: usize = 0x%02x{resultCountOffset};"
          $"pub const SCRATCH_OFFSET: usize = 0x%02x{scratchOffset};"
          $"pub const FRAME_CYCLES_OFFSET: usize = 0x%02x{Pod.frameCyclesOffset};"
          $"pub const FB_OFFSET: usize = 0x%04x{fbOffset};"
          $"pub const FB_WINDOW_WORDS: usize = %d{1 <<< fbAddrWidth};"
          $"pub const FB_PIXELS: usize = %d{mandelWidth * mandelHeight};"
          $"pub const APERTURE_BYTES: usize = %d{1 <<< apertureAddrWidth};"
          $"pub const FRAME_WIDTH: usize = %d{mandelWidth};"
          $"pub const FRAME_HEIGHT: usize = %d{mandelHeight};"
          $"pub const MAX_ITER: u32 = %d{mandelMaxIter};"
          "" ]

/// The full-scale wrapper's generated Rust layout — the frame seam, same
/// pattern as the mini pod's.
let private mandelFrameLayoutRs () =
    let widthPadded = paddedWidth frameFullWidth

    String.concat
        "\n"
        [ "//! Register map for the `MandelFrameAxi` AXI-Lite slave (the full-scale"
          $"//! frame accelerator; addrWidth=%d{frameApertureAddrWidth}). The framebuffer is NOT in the"
          "//! aperture — the fabric writes it to PS DDR at FB_BASE_ADDR_OFFSET's value."
          "//! Generated by `dotnet run -- hardware <repo-root>` in hdl."
          "//! Do not edit by hand — changes will be overwritten on next emit."
          ""
          $"pub const ID_OFFSET: usize = 0x%02x{frameStartOffset}; // reads as ID; writes pulse start"
          $"pub const ID_MAGIC: u32 = 0x%08x{frameIdMagic};"
          $"pub const START_OFFSET: usize = 0x%02x{frameStartOffset};"
          $"pub const BUSY_OFFSET: usize = 0x%02x{frameBusyOffset};"
          $"pub const DONE_OFFSET: usize = 0x%02x{frameDoneOffset}; // sticky; cleared by start"
          $"pub const CX_ORIGIN_OFFSET: usize = 0x%02x{frameCxOffset};"
          $"pub const CY_ORIGIN_OFFSET: usize = 0x%02x{frameCyOffset};"
          $"pub const DX_OFFSET: usize = 0x%02x{frameDxOffset};"
          $"pub const DY_OFFSET: usize = 0x%02x{frameDyOffset};"
          $"pub const LAST_FRAME_CYCLES_OFFSET: usize = 0x%02x{FrameAxi.frameCyclesOffset};"
          $"pub const FB_BASE_ADDR_OFFSET: usize = 0x%02x{frameFbBaseOffset};"
          $"pub const APERTURE_BYTES: usize = %d{1 <<< frameApertureAddrWidth};"
          $"pub const FRAME_WIDTH: usize = %d{frameFullWidth};"
          $"pub const FRAME_HEIGHT: usize = %d{frameFullHeight};"
          $"pub const WIDTH_PADDED: usize = %d{widthPadded};"
          $"pub const FB_BYTES: usize = %d{frameFullHeight * widthPadded}; // 1 byte/px, rows padded"
          $"pub const MAX_ITER: u32 = %d{frameFullMaxIter};"
          $"pub const NUM_LANES: usize = %d{frameFullLanes};"
          $"pub const FRAC_BITS: u32 = %d{frameFullFracBits};"
          "" ]

/// `dotnet run -- hardware <repo-root>`: the seam, emitted — both apps. The
/// Verilog goes where Vivado sources it; the layouts go where the Rust driver
/// owns them.
let writeHardware (repoRoot: string) =
    let buildDir = System.IO.Path.Combine(repoRoot, "hardware", "build")
    let runtimeSrc = System.IO.Path.Combine(repoRoot, "runtime", "core", "src")
    System.IO.Directory.CreateDirectory buildDir |> ignore

    let emitPair (verilogName: string) (design: ModuleDef) (layoutName: string) (layout: string) =
        let verilogPath = System.IO.Path.Combine(buildDir, verilogName)
        let layoutPath = System.IO.Path.Combine(runtimeSrc, layoutName)
        System.IO.File.WriteAllText(verilogPath, emitDesign design + "\n")
        System.IO.File.WriteAllText(layoutPath, layout)
        printfn $"wrote {verilogPath}"
        printfn $"wrote {layoutPath}"

    emitPair "MandelPodAxi.v" mandelPodAxi "mandel_layout.rs" (mandelLayoutRs ())
    emitPair "MandelFrameAxi.v" mandelFrameAxiFull.Value "mandel_frame_layout.rs" (mandelFrameLayoutRs ())
