<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <WarningsAsErrors>FS0025</WarningsAsErrors>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="Main.fs"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="../Warp11/Warp11.fsproj"/>
        <ProjectReference Include="../Warp11.Tutorial/Warp11.Tutorial.fsproj"/>
        <ProjectReference Include="../Warp11.SimView.Desktop/Warp11.SimView.Desktop.fsproj"/>
    </ItemGroup>

</Project>
