PACKAGE_NAME="u-dma-buf"
PACKAGE_VERSION="5.5.0"
BUILT_MODULE_NAME[0]="u-dma-buf"
DEST_MODULE_LOCATION[0]="/updates"
MAKE[0]="make -C ${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build KERNEL_SRC_DIR=${kernel_source_dir} all"
CLEAN="make -C ${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build KERNEL_SRC_DIR=${kernel_source_dir} clean"
AUTOINSTALL="yes"
