#!/usr/bin/env bash
# The open Lattice toolchain — yosys, nextpnr, icestorm, Trellis — for the
# iCE40 target. Development only, the same standing as firtool: no user-facing
# warp11 path touches it, and nothing in the differential oracle depends on it.
#
# Pinned, checksummed, and installed without root. Re-running is safe: it stops
# early if the wrapper already reports the pinned version.
#
# Why not the distribution package: Ubuntu noble ships yosys 0.33 (2023), which
# **dies with an internal assertion** on the audio designs —
#   Assert `nusers(O.extract_end(i)) <= 1' failed in ice40_dsp_pm.h:388
# — in the iCE40 DSP inference pass, on any design with wide multiplies. That is
# `MultibandStage`, which is the design the whole iCE40 question is about. The
# distribution package also splits yosys from nextpnr, and a version skew
# between them is a real failure mode once you are past `stat` and building
# bitstreams: this tarball ships them matched.
set -euo pipefail

version=2026-08-20
stamp=20260820
sha256=f85ffd027fc45cfacb7d6473cc4f815fa9829c527bb8b23ec653c37ced0c8859
asset=oss-cad-suite-linux-x64-$stamp.tgz

root=${OSS_CAD_HOME:-$HOME/tools/oss-cad-suite}
bindir=${OSS_CAD_BIN:-$HOME/tools/bin}
suite="$root/oss-cad-suite"

# The tools worth putting on PATH. The tarball carries well over a hundred
# binaries; wrapping only these keeps $bindir readable and makes it obvious
# which ones warp11 actually reaches for. The rest stay reachable inside the
# suite, and the wrappers put the suite's own bin first so sub-tools that these
# shell out to — abc, most of all — resolve to their matched versions.
tools=(yosys nextpnr-ice40 nextpnr-ecp5 icepack icetime icebram iceprog ecppack)

# The installed release is recorded in a stamp file rather than read back out
# of `yosys -V`: the suite is dated but the tools inside carry their own
# upstream versions (this release reports "Yosys 0.68+106"), so there is no
# version string to match the pin against.
installed="$root/.warp11-version"

if [ -x "$bindir/yosys" ] && [ "$(cat "$installed" 2>/dev/null)" = "$version" ]; then
    echo "oss-cad-suite $version already installed at $bindir/yosys"
    exit 0
fi

mkdir -p "$root" "$bindir"
work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT

# Normally downloaded. OSS_CAD_TARBALL points at an already-fetched copy, which
# is what makes a re-install or an offline machine cost nothing — the asset is
# 700 MB and the checksum below is verified either way, so this is a cache and
# not a way around the pin.
if [ -n "${OSS_CAD_TARBALL:-}" ]; then
    echo "using $OSS_CAD_TARBALL"
    tarball=$OSS_CAD_TARBALL
else
    tarball=$work/$asset
    url="https://github.com/YosysHQ/oss-cad-suite-build/releases/download/$version/$asset"
    echo "downloading $asset (700 MB, unpacks to ~2.5 GB)"
    curl -fL -o "$tarball" "$url"
fi

# Pinned here rather than fetched beside the tarball, for the reason
# install-firtool.sh gives: a checksum the same server hands you proves only
# that the download completed.
echo "$sha256  $tarball" | sha256sum -c -

echo "unpacking"
tar xzf "$tarball" -C "$root"

for tool in "${tools[@]}"; do
    if [ ! -x "$suite/bin/$tool" ]; then
        echo "warning: $tool is not in this release, skipping its wrapper" >&2
        continue
    fi
    cat > "$bindir/$tool" <<EOF
#!/bin/sh
# Generated by hdl/tools/install-oss-cad-suite.sh — oss-cad-suite $version.
# The suite's own bin goes first so sub-tools resolve to the matched build
# rather than to whatever the distribution installed, and it is scoped to this
# process so nothing else on the system sees it.
#
# Deliberately no LD_LIBRARY_PATH, unlike the firtool wrapper next door. These
# binaries carry their own RPATH and ship a complete lib/; putting that
# directory on the loader path makes system libraries resolve against the
# suite's incompatible copies and **segfaults yosys on startup**. firtool needs
# the injection because its "static" build links a libz3 the release omits;
# this one needs the opposite.
PATH="$suite/bin:\$PATH"
export PATH
exec "$suite/bin/$tool" "\$@"
EOF
    chmod +x "$bindir/$tool"
done

echo "$version" > "$installed"

"$bindir/yosys" -V
echo "installed ${#tools[@]} wrappers in $bindir"
echo "add $bindir to PATH"
