#!/usr/bin/env bash
# firtool, for the differential oracle's third leg. CI and development only —
# no user-facing warp11 path touches it, and `run_differential.sh` narrows the
# oracle rather than failing when it is absent.
#
# Pinned, checksummed, and installed without root. Re-running is safe: it stops
# early if the wrapper already reports the pinned version.
set -euo pipefail

version=1.156.0
sha256=ccd8f20a1734fc7e415f13e1256f7a909849044871281358801749d8934965ae
asset=circt-full-static-linux-x64.tar.gz

root=${FIRTOOL_HOME:-$HOME/tools/circt}
bindir=${FIRTOOL_BIN:-$HOME/tools/bin}
wrapper="$bindir/firtool"

if [ -x "$wrapper" ] && "$wrapper" --version 2>/dev/null | grep -q "$version"; then
    echo "firtool $version already installed at $wrapper"
    exit 0
fi

mkdir -p "$root" "$bindir"
work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT

url="https://github.com/llvm/circt/releases/download/firtool-$version/$asset"
echo "downloading $asset (1.1 GB — the binary inside is 55 MB)"
curl -fsSL -o "$work/$asset" "$url"

# The checksum is pinned here rather than fetched beside the tarball: a
# checksum the same server hands you proves only that the download completed.
echo "$sha256  $work/$asset" | sha256sum -c -

# Only the binaries we use. Unpacking the rest costs a gigabyte for nothing.
#
# `circt-translate` is the other half of the lowering path: `firtool --ir-fir`
# lowers high FIRRTL into the subset warp11 reads but emits MLIR, and
# `circt-translate --export-firrtl` turns that back into `.fir` text.
tar xzf "$work/$asset" -C "$root" \
    "firtool-$version/bin/firtool" \
    "firtool-$version/bin/circt-translate"

# The "static" build still links libz3, which the release does not ship. Taken
# from the distribution package and kept beside the binary, where the wrapper's
# LD_LIBRARY_PATH can reach it without affecting anything else on the system.
( cd "$work" && apt-get download libz3-4 > /dev/null )
dpkg-deb -x "$work"/libz3-4_*.deb "$work/z3"
cp "$work"/z3/usr/lib/x86_64-linux-gnu/libz3.so.4* "$root/firtool-$version/bin/"

for tool in firtool circt-translate; do
    cat > "$bindir/$tool" <<EOF
#!/bin/sh
# Generated by hdl/tools/install-firtool.sh — CIRCT $version, with the libz3
# the release links against but does not ship. The library path is scoped to
# this process so nothing else on the system sees it.
DIR="$root/firtool-$version/bin"
LD_LIBRARY_PATH="\$DIR\${LD_LIBRARY_PATH:+:\$LD_LIBRARY_PATH}" exec "\$DIR/$tool" "\$@"
EOF
    chmod +x "$bindir/$tool"
done

"$wrapper" --version | head -2
echo "installed $wrapper and $bindir/circt-translate"
echo "add $bindir to PATH, or point run_differential.sh at it with FIRTOOL=$wrapper"
