<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="Modules.fs" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Warp11\Warp11.fsproj" />
    </ItemGroup>

</Project>
